# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='first_name',
            field=models.CharField(default=0, max_length=15),
        ),
        migrations.AddField(
            model_name='client',
            name='last_name',
            field=models.CharField(default=0, max_length=15),
        ),
    ]
