# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 10:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_auto_20170318_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='bank',
        ),
        migrations.AddField(
            model_name='bank',
            name='bank',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bank', to=settings.AUTH_USER_MODEL),
        ),
    ]
