# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_auto_20170318_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='bank',
        ),
        migrations.AddField(
            model_name='employee',
            name='bank',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='bank.Bank'),
        ),
    ]
